### PR TITLE
Introduced Utility Functions - Remove duplicate code snippets 

### PR DESCRIPTION
**Pull request by Phelms215**
## Context 

* Introduced utility function for Logging, SteamCMD and Discord Messaging 
* Remove redundant (copy & paste) code snippets 
* Remove nesting where possible
* Better Update/Install required logic
* Removed requirement for UPDATE_ON_BOOT for initial installation 

## Choices
* Clean up redundant code to make future enhancements easier to implement 
* Removed requirement for UPDATE_ON_BOOT if server installation is not detected (no PalServer.sh or appmanifest file) 

## Test instructions

1. Started with old server version, ran through reboots with UPDATE_ON_BOOT and AUTOUPDATE flags set
2. Started new server and validated installation
3. Tested backup script 
4. Tested discord messaging 
5. Tested logging 

## Checklist before requesting a review

* [X] I have performed a self-review of my code
* [ ] I've added documentation about this change to the README.
* [X] I've not introduced breaking changes.

### CODE REVIEW

**Comment by Phelms215** [comment]
This PR has been rebased onto the latest main to integrate recent changes. 
Conflicts have been resolved.
Added command for rcon-cli

**Comment by win5923** [comment]
I believe it's preferable to retain `rcon-cli`; otherwise, various adjustments will be required in the documentation.

**Comment by Phelms215** [comment]
> I believe it's preferable to retain `rcon-cli`; otherwise, various adjustments will be required in the documentation.

The change doesn't remove rcon-cli or adjust anything public, just provided a function wrapper so the config didn't need to be supplied a dozen times

**Comment by win5923** [comment]
> > I believe it's preferable to retain `rcon-cli`; otherwise, various adjustments will be required in the documentation.
> 
> 
> 
> The change doesn't remove rcon-cli or adjust anything public, just provided a function wrapper so the config didn't need to be supplied a dozen times 

You're right, I thought it was replacing rcon-cli with RCON. Thank you for clarifying！

**Review by thijsvanloef — APPROVED** [review]

**Pull request merged**
