### PR TITLE
Add version checking

### LINKED ISSUE #493: Docker release version checker in Image
**Is your feature request related to a problem? Please describe.**
Create a check when the server is starting to see if the user is running the latest image (e.g. 0.31.0)
And let the user know when an upgrade is available, link to a doc that shows the user how to upgrade.

### PR DESCRIPTION
**Pull request by xHyperElectric**
## Context 

Fixes #493 

To check if the container is up to date on start, and if not link to documentation for how to update the container.
## Choices

I created a VERSION file in /scripts and will use a GitHub action to update the version of that file. Then on container start (in start.sh) I query the GitHub API to check if the current version is equal to the tag of the latest version and if not I link to the docusaurus page for updating the container (this page hasn't been added yet)

## Test instructions

I shelled into my container and ran the commands inside of it.

## Checklist before requesting a review

- [x] I have performed a self-review/test of my code
- [ ] I've added documentation about this change to the [docs](https://github.com/thijsvanloef/palworld-server-docker/tree/main/docusaurus/docs).
- [x] I've not introduced breaking changes.
- [ ] My changes do not violate linting rules.

### CODE REVIEW

**Comment by xHyperElectric** [comment]
I am not sure how to go about changing the Github workflow file. I'm very new to Github actions. I know that something like:
```      - name: Update VERSION file
        run: echo "${{ steps.meta.outputs.version }}" > /scripts/VERSION```
could update the version file but I don't know how the order of the actions needs to be organized. That action /\ would have to be after the action determining the semvar version, but I wasn't sure if you can modify files after checkout of the repo.

**Comment by thijsvanloef** [comment]
@xHyperElectric I'll have some time to work on this tomorrow, but in the meantime you can take some inspiration from this: https://stackoverflow.com/questions/74694675/adding-a-git-tag-and-version-info-to-docker-image-during-github-actions-build

**Comment by xHyperElectric** [comment]
@thijsvanloef I'm unsure on how to proceed with the github action workflow

**Comment by thijsvanloef** [comment]
@xHyperElectric That is ok, I will take a look at this PR later

**Comment by thijsvanloef** [comment]
Decided to go another way with the version checking https://github.com/thijsvanloef/palworld-server-docker/pull/513

**Pull request closed without merging**
