### PR TITLE
Fix incorrect environment variable handling

### PR DESCRIPTION
**Pull request by beomseok-park**
## Context 

* Fix incorrect environment variable handling

## Choices

* In `PalWorldSettings.ini`, `ServerName`, `ServerDescription`, `AdminPassword`, `ServerPassword`, `PublicIP`, `Region`, and `BanListURL` should be enclosed in double quotes.
* Fix the incorrect handling of double quotes in `start.sh`.

## Test instructions

1. Stop the Palworld server.
2. Build the container.
3. Delete `<mount_folder>/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`.
4. Set a `SERVER_NAME` with spaces in the .env. e.g. SERVER_NAME="My Palworld Server"
5. Start the Palworld server.
6. Check the server name in the game.

## Checklist before requesting a review

* [ ] I have performed a self-review of my code
* [ ] I've added documentation about this change to the README.
* [ ] I've not introduced breaking changes.

### CODE REVIEW

**Review by thijsvanloef — CHANGES_REQUESTED** [review]
If the strings are already quoted, like in the examples:
```yaml
         - ADMIN_PASSWORD="adminPasswordHere"
         - SERVER_NAME="World of Pals"
         - SERVER_DESCRIPTION=""
 ```
 Then the whole PalWorldSettings.ini gets really wierd with quotes:
 ```ini
 ServerName=""World of Pals"",ServerDescription="""",AdminPassword=""adminPasswordHere"",ServerPassword=""worldofpals"",PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region=""
 ```
 A check needs to be implemented to see if the vars already have quotes, and if they do not already have quotes then they should be added.

**Comment by llnut** [comment]
Change the way environment variables to use the following syntax can fix it:
```
environment:
  ADMIN_PASSWORD: "adminPasswordHere"
  SERVER_NAME: "World of Pals"
  SERVER_DESCRIPTION: ""
```
Although this may not be good enough, alternatively, can use sed for additional processing [like this](https://github.com/thijsvanloef/palworld-server-docker/issues/210).

**Review by beomseok-park — COMMENTED** [review]
I have pushed a new commit that resolves the issue.

**Comment by Dashboy1998** [comment]
> If the strings are already quoted, like in the examples:
> 
> ```yaml
>          - ADMIN_PASSWORD="adminPasswordHere"
>          - SERVER_NAME="World of Pals"
>          - SERVER_DESCRIPTION=""
> ```
> 
> Then the whole PalWorldSettings.ini gets really wierd with quotes:
> 
> ```ini
> ServerName=""World of Pals"",ServerDescription="""",AdminPassword=""adminPasswordHere"",ServerPassword=""worldofpals"",PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region=""
> ```
> 
> A check needs to be implemented to see if the vars already have quotes, and if they do not already have quotes then they should be added.

[Docker Documentation](https://docs.docker.com/compose/compose-file/05-services/#environment) doesn't support `var="value"` but rather:
* `var: "value"`
* `var: value`
* `var=value`
It is worth noting that you can do `"var=value"` but it's not mentioned

**Review by thijsvanloef — APPROVED** [review]
thank you for your work. I've only updated the examples.

**Comment by JustusPan** [comment]
does this mean we should change our docker compose file manually to remove all double quote of values when update to 0.19.1?

**Comment by thijsvanloef** [comment]
@JustusPan Yes, but a check has been put in place that it should work either way

**Pull request merged**
