### PR TITLE
Add specific Box64 builds for common ARM64 hosts

### PR DESCRIPTION
**Pull request by sonroyaalmerol**
## Context 
This PR will mainly attempt to address #571.  The main changes are found on the base image and most of this PR are documentation changes. I have also removed `ARM_COMPATIBILITY_MODE` completely as it QEMU binaries has been removed from the base image.

Base image changes include:
- Box64 and Box86 updates
- Additional Box64 builds for specific devices including Oracle ARM and M1
- Added `ARM64_DEVICE` env var to specify which Box64 build is to be used

The documentation changes include:
- separating ARM64-exclusive env vars
- adding relevant Box64 env vars for stability tweaking
- update pages with `ARM_COMPATIBILITY_MODE` mentioned

I have also specified sane defaults for Box64 configurations on the Dockerfile to make sure it is set properly.

## Choices

- We had issues with QEMU so it didn't make any sense for it to stay on the base image.
- Separating the ARM64-exclusive env vars should make it less confusing for the users. 
- Having specific Box64 builds for common server hosts will allow us to make sure that we provide the best stability they can get. This should minimize the server crashes caused by the emulation.

## Test instructions

1. Tested it on my Oracle ARM server with `ARM64_DEVICE` set to `adlink`.

## Checklist before requesting a review

- [x] I have performed a self-review/test of my code
- [x] I've added documentation about this change to the [docs](https://github.com/thijsvanloef/palworld-server-docker/tree/main/docusaurus/docs).
- [x] I've not introduced breaking changes.
- [x] My changes do not violate linting rules.

### CODE REVIEW

**Comment by sonroyaalmerol** [comment]
@thijsvanloef do you mind publishing a test image tag for this PR?

**Comment by thijsvanloef** [comment]
Here is the image: `thijsvanloef/palworld-server-docker:arm-box64-test`

**Comment by sonroyaalmerol** [comment]
This is all I can do for this specific PR for now. For those still having issues, I added documentations for config tweaking. It's hard for me to figure out which combination of the Box64 configs would work for a specific device. I only have my Oracle ARM server as a reference.

Some combinations might work for others and some might not. I think all we can do is ask them to test different configurations themselves based on the documentation. I added a specific section for it on the known issues page.

**Comment by thijsvanloef** [comment]
Thank you so much for your work ❤️

**Pull request merged**
