### PR TITLE
Add ENABLE_RCON ENV option and RCON_PORT ENV option

### PR DESCRIPTION
**Pull request by xHyperElectric**
I believe I changed all instances of "PORT" to "GAME_PORT" to delineate from "RCON_PORT" and Query Port, I hope I didn't miss any.
This is my first experience writing docker files or using sed, so please check it to make sure I didn't make any mistakes.

### CODE REVIEW

**Comment by xHyperElectric** [comment]
Double check start.sh as I have 0 experience with sed and got help from ChatGPT. I'm afraid the ENABLE_RCON option has no safety for if RCONEnabled is already set to true in the file. Idk what sed does when it fails

**Comment by xHyperElectric** [comment]
I believe the file has to at minimum have this:
```[/Script/Pal.PalGameWorldSettings]
OptionSettings=()```
with the setting inside the parentheses which did not account for.

**Comment by Twinki14** [comment]
Probably shouldn't change `PORT` to `GAME_PORT`, that change will break any current configurations, maybe wouldn't be a problem for a major version bump, but considering how actively developed & released this docker image at the moment, I'd lean towards leaving it as `PORT` or allowing both `PORT` & `GAME_PORT` to exist, and adding a deprecation warning in the readme

#40 Is also brewing up some potential ways to properly support such a setting, without need to manually touch `PalServerSettings.ini`, I really don't like the idea of the dockerfile touching my `PalServerSettings.ini` at all since it could corrupt any changes made outside the container, like a persistent volume

**Comment by xHyperElectric** [comment]
> #40 Is also brewing up some potential ways to properly support such a setting, without need to manually touch `PalServerSettings.ini`, I really don't like the idea of the dockerfile touching my `PalServerSettings.ini` at all since it could corrupt any changes made outside the container, like a persistent volume

I see that, this is exciting

**Comment by thijsvanloef** [comment]
> Probably shouldn't change `PORT` to `GAME_PORT`, that change will break any current configurations, maybe wouldn't be a problem for a major version bump, but considering how actively developed & released this docker image at the moment, I'd lean towards leaving it as `PORT` or allowing both `PORT` & `GAME_PORT` to exist, and adding a deprecation warning in the readme about `PORT`

@Twinki14 You are absolutly correct, although I agree that GAME_PORT is a better name, I can't change it currently as it would break running servers.

**Comment by thijsvanloef** [comment]
Closing this MR, resolved in https://github.com/thijsvanloef/palworld-server-docker/pull/54

**Pull request closed without merging**
