### PR TITLE
fix: swap image.name to image.repository

### PR DESCRIPTION
**Pull request by anthr76**
## Context 

* 

Swapping `image.name` to `image.repository` which tends to be more widely used in popular helm charts. This also has the added benefit of allowing it to work with the renovatebot 

## Choices

* 

To be more in-line with popular helm charts and allow the renovatebot to manage dependencies. 

## Test instructions

1. 

Installing the helm chart

I'm not sure if automation will update the values markdown?

## Checklist before requesting a review

* [x] I have performed a self-review of my code
* [ ] I've added documentation about this change to the README.
* [ ] I've not introduced breaking changes. (Users will need to swap this in their values if they have it set)

### CODE REVIEW

**Comment by anthr76** [comment]
@Filipe-Souza should I run helm-docs manually?

**Comment by thijsvanloef** [comment]
@anthr76 Is this PR ready to merge?

**Comment by Filipe-Souza** [comment]
@anthr76 I personally use git pre-commit hooks to update the docs, running manually is fine also.

**Comment by anthr76** [comment]
Sounds good! In that case this is ready to merge.

**Pull request merged**
