### PR TITLE
Better compatibility for ARM64 hosts

### LINKED ISSUE #366: Container exits on MacOS / ARM64
## Describe the bug
I am trying to start the latest-arm64 container on an M1 MacBook Pro that has Rancher Desktop installed and configured.  I'm using compose to try and bring it up, and I get an error.

## To Reproduce

1. On an Apple Silicon Mac, setup Rancher Desktop https://rancherdesktop.io
2. Choose the nerdctl replacement for docker.
3. 'nerdctl compose up' with the docker-compose.yaml provided below. 

## Expected behavior

Expect the container to run and PalWorld Server to update and run. 

## Actual behavior

It appears to call box86 instead of box64 when running steamcmd, I think.  I was looking at this late and I need help, I think there's something broken in the underlying steamcmd-arm64 image.

```
$ nerdctl compose up
INFO[0000] Creating network jre_default                 
INFO[0000] Ensuring image thijsvanloef/palworld-server-docker:latest-arm64 
INFO[0000] Creating container Pal1                      
INFO[0000] Attaching to logs                            
Pal1 |*****EXECUTING USERMOD*****
INFO[0000] Container "Pal1" exited                      
INFO[0000] All the containers have exited               
INFO[0000] Stopping containers (forcibly)               
INFO[0000] Stopping container Pal1                      
```

## OS information

- OS:  macOS Sonoma 14.3.1
- Palworld Version:  1.4.1.0 
- Docker Image Version:  
``` $ nerdctl version
Client:
 Version:	v1.7.3
 OS/Arch:	linux/arm64
 Git commit:	0a464409d0178e16d3d2bed36222937ec3fc9c77
 buildctl:
  Version:	v0.12.5
  GitCommit:	bac3f2b673f3f9d33e79046008e7a38e856b3dc6

Server:
 containerd:
  Version:	v1.7.2
  GitCommit:	0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:	1.1.12
  GitCommit:	51d5e94601ceffbbd85688df1c928ecccbfa4685
```

## Hardware information
Screenshot 2024-02-11 at 1 41 27 PM

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest-arm64
      restart: always
      container_name: Pal1
      ports:
         - 25575:25575/tcp
         - 8215:8215/udp
         - 27015:27015/udp
      environment:
         - PUID=501
         - PGID=20
         - PUBLIC_IP=1.2.3.4
         - PUBLIC_PORT=8215
         - PORT=8215 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD="MacOS arm64 test" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="arm64-test"
         - COMMUNITY=true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="ARM64 on Mac PalWorld"
         - REGION="NA"
         - SERVER_DESCRIPTION="MacOS Container Test - M1 Pro 32GB"
         - BACKUP_ENABLED=true
         - IS_MULTIPLAYER=true
         - BACKUP_CRON_EXPRESION="0 0 * * *"
         - AUTO_UPDATE_ENABLED=true
         - AUTO_UPDATE_CRON_EXPRESSION="0 * * * *"
         - AUTO_UPDATE_WARN_MINUTES=30
         - AUTO_REBOOT_ENABLED=true
         - AUTO_REBOOT_WARN_MINUTES=15
         - AUTO_REBOOT_CRON_EXPRESSION="0 * * * *"
         - UPDATE_ON_BOOT=true
      volumes:
         - /Users/jre/palworld:/palworld/
```

## Container/Host Logs

```log
*****EXECUTING USERMOD*****
usermod: no changes
*****GENERATING CONFIGS*****
Compiling PalWorldSettings.ini...
Compiling PalWorldSettings.ini done!
*****STARTING INSTALL/UPDATE*****
/home/steam/steamcmd/steamcmd.sh: line 38: /usr/local/bin/box86: cannot execute binary file: Exec format error
cp: cannot stat './PalServer.sh': No such file or directory
sed: can't read ./PalServer-arm64.sh: No such file or directory
chmod: cannot access './PalServer-arm64.sh': No such file or directory
./PalServer-arm64.sh does not exist.
Try restarting with UPDATE_ON_BOOT=true
```
Note UPDATE_ON_BOOT=true is in the docker-compose.yaml

## Additional context

Rancher Desktop is a license unencumbered alternative to Docker Desktop and has better performance on MacOS supposedly.  Anyway, it's free to use.

### LINKED ISSUE #456: QNAP NAS - Container Station - Trouble getting Server up and Running on a ARM CPU
## Describe the bug

When Trying to run this Docker in Container Station on QNAP NAS (TS-932PX - ARM CPU) it wont start with the some errors
maybe its because of Container Station

## To Reproduce

Try to run this on a similar QNAP NAS (CPU is important)
Open Container Station, Pull the Image , make settings and try to start

## Expected behavior

Running a Server in Docker like on my TS-451 (Intel DualCore CPU, but its way to weak for the server xD)

## Actual behavior

stop executing the Docker Container cause of fails

## OS information

- OS:  Actual QTS 5.1.5.2679
- Palworld Version:  0.1.4.1
- Docker Image Version:  Docker version 20.10.27-qnap1, build 662936b

## Hardware information

- CPU:  Annapurnalabs Alpine AL-324 ARM® Cortex-A57 (Quad-Core 1,7Ghz)
- Memory:  16GB ddr3

## docker-compose.yml contents

not needed in Container Station

## Container/Host Logs

*****EXECUTING USERMOD*****
usermod: no changes
*****GENERATING CONFIGS*****
Compiling PalWorldSettings.ini...
Compiling PalWorldSettings.ini done!
*****STARTING INSTALL/UPDATE*****
/home/steam/steamcmd/steamcmd.sh: line 38: /usr/local/bin/box86: cannot execute binary file: Exec format error
cp: cannot stat './PalServer.sh': No such file or directory
sed: can't read ./PalServer-arm64.sh: No such file or directory
chmod: cannot access './PalServer-arm64.sh': No such file or directory
./PalServer-arm64.sh does not exist.
Try restarting with UPDATE_ON_BOOT=true
cli: config: parse file: read file: open rcon.yaml: no such file or directory

## Additional context

I´ve Setup 2 Folders for this container /palworld and /home , do i need to create more folders maybe?

### PR DESCRIPTION
**Pull request by sonroyaalmerol**
## Context 

* Box86, the default compatibility layer running steamcmd for game updates, is a 32-bit binary and is built for ARM, not ARM64. Some hosts are incapable of running Box86 due to this.
* QEMU user mode binaries are available as a native binary built for ARM64. The downside is that its performance is not fast enough to run the actual game server. However, it could most definitely be used for steamcmd only to download and update server files.
* Might close #366 and #456 

## Choices

* Add qemu-i386-static binary to the base image. This would mean going back to my base image as the current one does not have the said binary.
* Add ARM_COMPATIBILITY_MODE as an env option instead of changing the default to avoid breaking changes. Moving away from Box86 as default will also mean significantly slower build times so it would not be ideal for the test CI.
* ARM_COMPATIBILITY_MODE **might** allow you to proceed despite not having 4k page size. However, it is **not a guarantee**. It's the best option we currently have if we want to expand compatibility.
* Move page size checker within the InstallServer function as it is only relevant when steamcmd is executed to close #456.
* Since moving the page size checker allows users to "bypass" the restriction by skipping the update/install, Box64 binaries built for different page sizes (8k, 16k, and 64k) have been added to the base image. The script has also been modified to automatically swap the binary used accordingly.
* Add to known issues (documentation)

## Test instructions

1. Tested in known working ARM64 hosts and confirmed there are no breaking changes.
2. Tested by @Zarrsito and confirmed 64k page size works if steamcmd is bypassed.

## Checklist before requesting a review

* [x] I have performed a self-review of my code
* [x] I've added documentation about this change to the README.
* [x] I've not introduced breaking changes.

### CODE REVIEW

**Comment by sonroyaalmerol** [comment]
@Zarrsito do you mind testing this for me? i don't have a machine that can recreate your problem

**Comment by Zarrsito** [comment]
Sure! :D But what exactly do i need to do to test this ? when i try to pull the image with container station i get a choice what brand i want to download, do i have to select some special ?

**Comment by thijsvanloef** [comment]
@Zarrsito you can use the following image: `thijsvanloef/palworld-server-docker:pr-464`

**Comment by Zarrsito** [comment]
ive tested the above build and im getting this error ;

usermod: no changes
Only ARM64 hosts with 4k page size is supported.
****EXECUTING USERMOD****

QNAP changed page size to 64k

**Comment by thijsvanloef** [comment]
@Zarrsito if you pull `thijsvanloef/palworld-server-docker:pr-464` again, could you try again? The pagesize check was still there, should be gone.

**Comment by Zarrsito** [comment]
so i´ve tested, and this is the result:

****EXECUTING USERMOD****
usermod: no changes
ARM compatibility mode enabled
Server installation not detected.
****Starting Installation****
tid(29) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
**
ERROR:../../accel/tcg/cpu-exec.c:954:cpu_exec: assertion failed: (cpu == current_cpu)
Bail out! ERROR:../../accel/tcg/cpu-exec.c:954:cpu_exec: assertion failed: (cpu == current_cpu)
/home/steam/steamcmd/steamcmd.sh: line 39:    29 Trace/breakpoint trap   $DEBUGGER "$STEAMEXE" "$@"
cp: cannot stat './PalServer.sh': No such file or directory
sed: can't read ./PalServer-arm64.sh: No such file or directory
chmod: cannot access './PalServer-arm64.sh': No such file or directory
./PalServer-arm64.sh does not exist.
Server Not Installed Properly

do i need some special folders as workingspace for this ?

**Comment by Zarrsito** [comment]
!
Unbenannt

**Comment by sonroyaalmerol** [comment]
@Zarrsito Okay, I didn't realize you were not using the latest tag when you submitted the issue. This fix is meant for those with CPUs that are only capable of executing ARM64 binaries without an additional compatibility layer (mostly those who are not running Docker Desktop) which I believe is the problem for those in issue #366. I thought you had the same issue.

I'll revert the page size check change as it was the expected behaviour.

**Comment by Zarrsito** [comment]
what do u mean with latest tag? =) i´ve answered the questions as good as possible :) 

thijsvanloef/palworld-server-docker:pr-464
is now the first docker container not resulting in an exec error, for me
and i´ve tested all avaiable images in the docker store...

i wonder what this . folder should be < ./PalServer-arm64.sh does not exist. >
its not possible for me to make a workspace . in container-station

**Comment by sonroyaalmerol** [comment]
Don't worry about it. Your answers were perfect. It was just a misunderstanding on my part. This specific fix is not for your problem. If using the `latest` tag gives you a page size error, then that is most likely your problem and there's nothing we can do about it on our side. I've explained more about this in the issue you submitted.

**Comment by thijsvanloef** [comment]
@sonroyaalmerol I can't really test this PR, are you confident that it has been tested enough?

**Comment by sonroyaalmerol** [comment]
I can say that this PR will not affect existing ARM64 users. It's more of adding a different option for people to try if they had an ARM64 host that didn't work previously. It shouldn't have any breaking changes.

**Pull request merged**
