### PR TITLE
Update: Enhanced compilation scripts

### PR DESCRIPTION
**Pull request by celaraze**
~~1: Add a build-time architecture parameters below:~~

| ~~ARGs~~ | ~~Default~~ | ~~Available~~    |
|------|---------|---------------|
| ~~ARCH~~ | ~~amd64~~   | ~~amd64, arm64~~  |
| ~~OS~~   | ~~linux~~   | ~~linux, darwin~~ |

~~If we need to build a macOS Silicon image should be though `docker build --build-arg ARCH=arm64 --build-arg OS=darwin -t user/image:tag .` .~~
~~2: Add priority to determine whether the current architecture is supported, and exit after an exception.~~
3: Controllable `SUPERCRONIC` and `RCON` version numbers.
4: Remove the `-q` parameter of `wget`, instead of `wget --progress=dot:giga`, which is especially important for the visualization of logs during the compilation process.
5: Unified, highly readable code and comments.
6: Add `md5sum` for `RCON`.

### CODE REVIEW

**Comment by Technetium1** [comment]
Why remove checksum validation?

**Comment by celaraze** [comment]
> Why remove checksum validation?

It's hard-coded in the script and only the amd64 binaries are validated, and I'm constantly updating this PR so that multiple binaries across platforms can be checked.

**Comment by celaraze** [comment]
COME ON. The ARM platform is irrelevant, because of the `cm2network/steamcmd` image is only `amd64` architecture.
deleted for 1 and 2.

**Comment by thijsvanloef** [comment]
Made some revision:

- Add labels to the docker image
- Sort package installs alphabetically 
- Split Rcon and Supercronic install

**Comment by celaraze** [comment]
> Made some revision:
> 
> * Add labels to the docker image
> * Sort package installs alphabetically
> * Split Rcon and Supercronic install

gotcha, thanks.

btw, conflicts resolved.

**Review by thijsvanloef — APPROVED** [review]
LGTM

**Pull request merged**
