### PR TITLE
docs: add french language to documentation

### PR DESCRIPTION
**Pull request by Strawbang**
## Context 

* 
Hello, i just translate the documentation official in french

## Choices

* 

## Test instructions

1. 

## Checklist before requesting a review

* [ x] I have performed a self-review of my code
* [ x] I've added documentation about this change to the README.
* [x ] I've not introduced breaking changes.

### CODE REVIEW

**Comment by thijsvanloef** [comment]
Hi Strawbang, thank you for taking the time to translate, if you are able to, are you willing to also translate the docusaurus docs?
https://palworld-server-docker.loef.dev/help-translate/

**Comment by Strawbang** [comment]
> Hi Strawbang, thank you for taking the time to translate, if you are able to, are you willing to also translate the docusaurus docs? https://palworld-server-docker.loef.dev/help-translate/
> 
> This is because i am planning on sunsetting these docs, and moving everything to docusaurus

Thanks you, I can also translate. Do you think I should open a new PR for the next stage?

**Comment by thijsvanloef** [comment]
Yes please open a new PR for that change :)

**Comment by Strawbang** [comment]
> I was unable to fix the links in markdown, @Strawbang do you mind looking over those?

Yes i go to check the links

**Pull request merged**
